### ISSUE TITLE
error: An organization slug is required (provide with --org)

### ISSUE THREAD

**Issue by wollenszhang** [kamilogorek/sentry-typescript-sourcemaps#1]
Hi, trying to upload sourcemap to sentry, but catch this error:
when i run sentry-typescript-sourcemaps example
~~~
ERROR in Sentry CLI Plugin: Command failed: /Users/kiwibase/Desktop/code/gitlab/testGitCode/sentry-typescript-sourcemaps/node_modules/@sentry/cli/sentry-cli releases new c3ffc0f0d1ca63d904e4eade8ecbac9f6268b77a
error: An organization slug is required (provide with --org)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
~~~
There is how i use sentryclirc plugin:
~~~
[defaults]
project=xxxx
url=https://sentry.io/
org=xxxx

[auth]
token=xxxxxxx
~~~
Version:
`"@sentry/cli": "^1.46.0"`

**Comment by kamilogorek** [comment]
Just tested it locally and everything works fine. Did you copy `.sentryclirc.example` to `.sentryclirc`? (remember about leading dot!)

**Comment by wollenszhang** [comment]
Yes but  it's wrong i have so sod

**Comment by wollenszhang** [comment]
you can show me a detailed typescript program link for sentry?

**Comment by kamilogorek** [comment]
https://github.com/getsentry/sentry-cli/
https://github.com/getsentry/sentry-webpack-plugin/

https://docs.sentry.io/cli/configuration/
